language: java
install: true
jdk:
- openjdk8
- openjdk11
before_install:
- chmod +x gradlew
stages:
- name: build
- name: publish-snapshot
  if: branch = master AND type IN (push)
- name: publish-release
  if: branch =~ ^release\/.*$ AND type IN (push)
jobs:
  include:
  - stage: build
    script: "./gradlew build coveralls --continue"
  - stage: publish-snapshot
    script: "./gradlew artifactoryPublish -x test -Dsnapshot=true -Dbuild.number=$TRAVIS_BUILD_NUMBER"
  - stage: publish-release
    script: "./gradlew bintrayUpload -x test -Dbuild.number=$TRAVIS_BUILD_NUMBER"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: Kg+waccPDKgGpwuetKJCECAJJ3C/aJPENMV0eAg3vAW1wnWL5aKhAggTAjq8pLwVtT+V9oIjZvTiBZxqcnl4GdDijA1I1A9dblJttMICtiPPihE8kp7N3TGeebfn1zqXjFqpcR2D2ItD3mnQgAM43XIXkBfaM6S4tZMx3OJXW1fmRzXnL0FNvMWNsWvhZ0X9ZRQ8feg5RZb4Wrd1JYPqANxGJ65vwS0Wv8U+GvTi9INPThnq+1LL+0347xDZp25py0UZvYJ2Qp/+6uVsCy0jZgOdmOMBWY9sm0XKE7QRrmLJxsxaVLml2ZJfzrR+QByLQcIolB8Hku20C7JsB/Zc92dgU6nsfQ2qNLuTAuhrmU0jpSIWeBrsvec91/ayXOqslixjutGSG5+BToOIdH8ETOiVOYDXrdmEAllm+hfZynDtIHLBX6HsiC286pVhu0f98DG1up2H+YSmzhQsUJZsjCLMJJ1raK2tkNab25sm8sd6v0w5S4uy75dMe9augVT1oRH3Ty/QRxUHbfayLHs2oYs51AvhXL+Fj5Oxgh3AoIrv2eYoSYCyVWjJthD6O77Dx/NHLN9a/FHL9/D5ngtpeQzJIoV+jo9VMlca83Dtix3mS+0J3qXIPcH79X8b0hUIk4ahkJEHhxDCw15/gqM3cPGvY80zobMssJa5n2sgifk=
  - secure: GBFJm7LOHDde7OMv4TR0voVIcp4n60ORrusqvpEjpoCq917Q2kbWnMscfDRYZ13SlR5AVgvnq5D/7bGyRxbnvT4vtf1+2FWviIXS0xvodZuPzC/XiMZSRRRN/oBzS9RZyciZUD49w9a8+Lr4vHFWG30uruP4Ma9FKeNvt3+UEhTOPdpAVXiLNo4nywBBuhqT0W9nn5WTwMNBfVhDcCsJ9S8+n4wX+4Rzq0uDybeU+cqinhtDmPb4Vph/+rcKvXcckKO0MbeCamBKJXy2pje7tuG1dV5JmGebp3rPraT5acbFc14PPcQKRYTmJNp3/mIJ2b++zzg1B9ufHv68B1gcsAQIo4KLs/fN9f9rP+/L9h67YV1jHR1oHiLR0uimom0n0HGd0oCgwlegT4reqFxLBftGFNJxrTayE+/VogB3IA3QRw+TxBffz+cZZZ3z/WT7EYwLOmpJYLWrpSGrx6D2nbOUDHhFSLvoGFGd01+UQj1+P5E9mJvFCvmCcmh7S/binwGYsZyi3mLfljxZ9r/9Q1PN8c18gaBPsGfgrdmEts8p5oEng7WpcBDmF1Hn90pGGODuUR9n5t00way0h38mT5K+yAPziSEwfRrFFSF9xRXZaaKbiESrflFvv613q9MZ/DRur/iU2hAaYzgOvG/bdfaf34bwqcq1ZzexvBt0H+A=
